[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Route nice paths to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Scheduled prewarm at 17:15 IST (11:45 UTC) on weekdays
[functions."prewarm"]
  schedule = "45 11 * * 1-5"

# Security headers for API (you can tighten the origin later)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type,Authorization"

